site_name: 100 Days of Deep Learning
site_author: Rudra Prasad Bhuyan
site_description: |
  All the nots, code, usefull sources i collected thourght out this 
  journey i will share with you.
#site_url: https://example.com
repo_url: https://github.com/Rudra-G-23/100-days-of-deep-learning
repo_name: Rudra-G-23/100-days-of-deep-learning
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Rudra Prasad Bhuyan. All rights reserved.

# Theme
theme:
  name: material
  icon:
    annotation: material/star-four-points-circle
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    #- content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate

  palette:
    - scheme: default
      primary: '#5e17eb'   
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: '#5e17eb'
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-heart

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  #- git-revision-date-localized:
      #enable_creation_date: true
      #fallback_to_build_date: true
      #enable_git_follow: false

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
# From mkdocs: https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-docsjavascriptsmathjaxjs 
extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - js/katex_init.js   
  - js/shortcuts.js 

# Social Media Links 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Rudra-G-23/100-days-of-deep-learning
      name: Github
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Rudra_love_with_data
      name: YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rudra-prasad-bhuyan-44a388235/
      name: LinkedIn
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/rudraprasadbhuyan
      name: Kaggle
    - icon: fontawesome/brands/pinterest
      link: https://in.pinterest.com/rudraprasadbhuyan23
      name: Pinterest

nav:
  - Home: index.md

  - Help:
      - Keyboard Shortcuts: help/keyboard-shortcuts.md

  - Basics:
      - Introduction: basic-of-dl/introduction.md
      - Types of Deep Learning: basic-of-dl/types-of-dl.md

  - Perceptron:
      - Perceptron Basics: perceptron/perceptron-basic.md
      - Perceptron Trick: perceptron/perceptron-trick.md
      - Perceptron Trick Algorithm: perceptron/perceptron-trick-algorithm.md
      - Perceptron Loss Function: perceptron/perceptron-loss-function.md
      - Gradient Descent for Perceptron: perceptron/gradient-descent-for-perceptron.md
      - More Loss Functions: perceptron/more-loss-function.md
      - Problem with Perceptron: perceptron/problem-with-perceptron.md

  - MLP:
      - MLP Intuition: mlp/mlp-intuition.md
      - MLP Notation: mlp/mlp-notation.md
      - Forward Propagation: mlp/forward-propagation.md

  - Backpropagation:
      - The What: backpropagation/the-what.md
      - The Why: backpropagation/the-why.md
      - The How: backpropagation/the-how.md